#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yxxt_data")]
	public partial class dormitoryModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertFresh_Bed_Log(Fresh_Bed_Log instance);
    partial void UpdateFresh_Bed_Log(Fresh_Bed_Log instance);
    partial void DeleteFresh_Bed_Log(Fresh_Bed_Log instance);
    #endregion
		
		public dormitoryModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yxxt_dataConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fresh_Bed_Log> Fresh_Bed_Logs
		{
			get
			{
				return this.GetTable<Fresh_Bed_Log>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Bed_Log")]
	public partial class Fresh_Bed_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Bed_Log;
		
		private string _FK_Bed_NO;
		
		private string _FK_SNO;
		
		private string _Updater;
		
		private System.Nullable<System.DateTime> _Update_DT;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Bed_LogChanging(string value);
    partial void OnPK_Bed_LogChanged();
    partial void OnFK_Bed_NOChanging(string value);
    partial void OnFK_Bed_NOChanged();
    partial void OnFK_SNOChanging(string value);
    partial void OnFK_SNOChanged();
    partial void OnUpdaterChanging(string value);
    partial void OnUpdaterChanged();
    partial void OnUpdate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_DTChanged();
    #endregion
		
		public Fresh_Bed_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Bed_Log", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Bed_Log
		{
			get
			{
				return this._PK_Bed_Log;
			}
			set
			{
				if ((this._PK_Bed_Log != value))
				{
					this.OnPK_Bed_LogChanging(value);
					this.SendPropertyChanging();
					this._PK_Bed_Log = value;
					this.SendPropertyChanged("PK_Bed_Log");
					this.OnPK_Bed_LogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Bed_NO", DbType="NVarChar(50)")]
		public string FK_Bed_NO
		{
			get
			{
				return this._FK_Bed_NO;
			}
			set
			{
				if ((this._FK_Bed_NO != value))
				{
					this.OnFK_Bed_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Bed_NO = value;
					this.SendPropertyChanged("FK_Bed_NO");
					this.OnFK_Bed_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SNO", DbType="NVarChar(20)")]
		public string FK_SNO
		{
			get
			{
				return this._FK_SNO;
			}
			set
			{
				if ((this._FK_SNO != value))
				{
					this.OnFK_SNOChanging(value);
					this.SendPropertyChanging();
					this._FK_SNO = value;
					this.SendPropertyChanged("FK_SNO");
					this.OnFK_SNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updater", DbType="NVarChar(20)")]
		public string Updater
		{
			get
			{
				return this._Updater;
			}
			set
			{
				if ((this._Updater != value))
				{
					this.OnUpdaterChanging(value);
					this.SendPropertyChanging();
					this._Updater = value;
					this.SendPropertyChanged("Updater");
					this.OnUpdaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> Update_DT
		{
			get
			{
				return this._Update_DT;
			}
			set
			{
				if ((this._Update_DT != value))
				{
					this.OnUpdate_DTChanging(value);
					this.SendPropertyChanging();
					this._Update_DT = value;
					this.SendPropertyChanged("Update_DT");
					this.OnUpdate_DTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
