#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yxxt_data")]
	public partial class dormitoryModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertFresh_Room(Fresh_Room instance);
    partial void UpdateFresh_Room(Fresh_Room instance);
    partial void DeleteFresh_Room(Fresh_Room instance);
    partial void InsertFresh_Bed_Log(Fresh_Bed_Log instance);
    partial void UpdateFresh_Bed_Log(Fresh_Bed_Log instance);
    partial void DeleteFresh_Bed_Log(Fresh_Bed_Log instance);
    partial void InsertFresh_Dorm(Fresh_Dorm instance);
    partial void UpdateFresh_Dorm(Fresh_Dorm instance);
    partial void DeleteFresh_Dorm(Fresh_Dorm instance);
    partial void InsertFresh_Bed_Type(Fresh_Bed_Type instance);
    partial void UpdateFresh_Bed_Type(Fresh_Bed_Type instance);
    partial void DeleteFresh_Bed_Type(Fresh_Bed_Type instance);
    partial void InsertFresh_Bed(Fresh_Bed instance);
    partial void UpdateFresh_Bed(Fresh_Bed instance);
    partial void DeleteFresh_Bed(Fresh_Bed instance);
    partial void InsertFresh_Room_Type(Fresh_Room_Type instance);
    partial void UpdateFresh_Room_Type(Fresh_Room_Type instance);
    partial void DeleteFresh_Room_Type(Fresh_Room_Type instance);
    #endregion
		
		public dormitoryModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yxxt_dataConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dormitoryModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Fresh_Room> Fresh_Rooms
		{
			get
			{
				return this.GetTable<Fresh_Room>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Bed_Log> Fresh_Bed_Logs
		{
			get
			{
				return this.GetTable<Fresh_Bed_Log>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Dorm> Fresh_Dorms
		{
			get
			{
				return this.GetTable<Fresh_Dorm>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Bed_Type> Fresh_Bed_Types
		{
			get
			{
				return this.GetTable<Fresh_Bed_Type>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Bed> Fresh_Beds
		{
			get
			{
				return this.GetTable<Fresh_Bed>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Room_Type> Fresh_Room_Types
		{
			get
			{
				return this.GetTable<Fresh_Room_Type>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Room")]
	public partial class Fresh_Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Room_NO;
		
		private string _Room_NO;
		
		private string _FK_Dorm_NO;
		
		private string _Floor;
		
		private string _Gender;
		
		private string _FK_Room_Type;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Room_NOChanging(string value);
    partial void OnPK_Room_NOChanged();
    partial void OnRoom_NOChanging(string value);
    partial void OnRoom_NOChanged();
    partial void OnFK_Dorm_NOChanging(string value);
    partial void OnFK_Dorm_NOChanged();
    partial void OnFloorChanging(string value);
    partial void OnFloorChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnFK_Room_TypeChanging(string value);
    partial void OnFK_Room_TypeChanged();
    #endregion
		
		public Fresh_Room()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Room_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Room_NO
		{
			get
			{
				return this._PK_Room_NO;
			}
			set
			{
				if ((this._PK_Room_NO != value))
				{
					this.OnPK_Room_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Room_NO = value;
					this.SendPropertyChanged("PK_Room_NO");
					this.OnPK_Room_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_NO", DbType="NVarChar(20)")]
		public string Room_NO
		{
			get
			{
				return this._Room_NO;
			}
			set
			{
				if ((this._Room_NO != value))
				{
					this.OnRoom_NOChanging(value);
					this.SendPropertyChanging();
					this._Room_NO = value;
					this.SendPropertyChanged("Room_NO");
					this.OnRoom_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Dorm_NO", DbType="NVarChar(50)")]
		public string FK_Dorm_NO
		{
			get
			{
				return this._FK_Dorm_NO;
			}
			set
			{
				if ((this._FK_Dorm_NO != value))
				{
					this.OnFK_Dorm_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Dorm_NO = value;
					this.SendPropertyChanged("FK_Dorm_NO");
					this.OnFK_Dorm_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Floor", DbType="NVarChar(50)")]
		public string Floor
		{
			get
			{
				return this._Floor;
			}
			set
			{
				if ((this._Floor != value))
				{
					this.OnFloorChanging(value);
					this.SendPropertyChanging();
					this._Floor = value;
					this.SendPropertyChanged("Floor");
					this.OnFloorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Room_Type", DbType="NVarChar(50)")]
		public string FK_Room_Type
		{
			get
			{
				return this._FK_Room_Type;
			}
			set
			{
				if ((this._FK_Room_Type != value))
				{
					this.OnFK_Room_TypeChanging(value);
					this.SendPropertyChanging();
					this._FK_Room_Type = value;
					this.SendPropertyChanged("FK_Room_Type");
					this.OnFK_Room_TypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Bed_Log")]
	public partial class Fresh_Bed_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Bed_Log;
		
		private string _FK_Bed_NO;
		
		private string _FK_SNO;
		
		private string _Updater;
		
		private System.Nullable<System.DateTime> _Update_DT;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Bed_LogChanging(string value);
    partial void OnPK_Bed_LogChanged();
    partial void OnFK_Bed_NOChanging(string value);
    partial void OnFK_Bed_NOChanged();
    partial void OnFK_SNOChanging(string value);
    partial void OnFK_SNOChanged();
    partial void OnUpdaterChanging(string value);
    partial void OnUpdaterChanged();
    partial void OnUpdate_DTChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdate_DTChanged();
    #endregion
		
		public Fresh_Bed_Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Bed_Log", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Bed_Log
		{
			get
			{
				return this._PK_Bed_Log;
			}
			set
			{
				if ((this._PK_Bed_Log != value))
				{
					this.OnPK_Bed_LogChanging(value);
					this.SendPropertyChanging();
					this._PK_Bed_Log = value;
					this.SendPropertyChanged("PK_Bed_Log");
					this.OnPK_Bed_LogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Bed_NO", DbType="NVarChar(50)")]
		public string FK_Bed_NO
		{
			get
			{
				return this._FK_Bed_NO;
			}
			set
			{
				if ((this._FK_Bed_NO != value))
				{
					this.OnFK_Bed_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Bed_NO = value;
					this.SendPropertyChanged("FK_Bed_NO");
					this.OnFK_Bed_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SNO", DbType="NVarChar(20)")]
		public string FK_SNO
		{
			get
			{
				return this._FK_SNO;
			}
			set
			{
				if ((this._FK_SNO != value))
				{
					this.OnFK_SNOChanging(value);
					this.SendPropertyChanging();
					this._FK_SNO = value;
					this.SendPropertyChanged("FK_SNO");
					this.OnFK_SNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updater", DbType="NVarChar(20)")]
		public string Updater
		{
			get
			{
				return this._Updater;
			}
			set
			{
				if ((this._Updater != value))
				{
					this.OnUpdaterChanging(value);
					this.SendPropertyChanging();
					this._Updater = value;
					this.SendPropertyChanged("Updater");
					this.OnUpdaterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Update_DT", DbType="DateTime")]
		public System.Nullable<System.DateTime> Update_DT
		{
			get
			{
				return this._Update_DT;
			}
			set
			{
				if ((this._Update_DT != value))
				{
					this.OnUpdate_DTChanging(value);
					this.SendPropertyChanging();
					this._Update_DT = value;
					this.SendPropertyChanged("Update_DT");
					this.OnUpdate_DTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Dorm")]
	public partial class Fresh_Dorm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Dorm_NO;
		
		private string _Dorm_NO;
		
		private string _Year;
		
		private string _Name;
		
		private string _Campus_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Dorm_NOChanging(string value);
    partial void OnPK_Dorm_NOChanged();
    partial void OnDorm_NOChanging(string value);
    partial void OnDorm_NOChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCampus_NOChanging(string value);
    partial void OnCampus_NOChanged();
    #endregion
		
		public Fresh_Dorm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Dorm_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Dorm_NO
		{
			get
			{
				return this._PK_Dorm_NO;
			}
			set
			{
				if ((this._PK_Dorm_NO != value))
				{
					this.OnPK_Dorm_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Dorm_NO = value;
					this.SendPropertyChanged("PK_Dorm_NO");
					this.OnPK_Dorm_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dorm_NO", DbType="NVarChar(20)")]
		public string Dorm_NO
		{
			get
			{
				return this._Dorm_NO;
			}
			set
			{
				if ((this._Dorm_NO != value))
				{
					this.OnDorm_NOChanging(value);
					this.SendPropertyChanging();
					this._Dorm_NO = value;
					this.SendPropertyChanged("Dorm_NO");
					this.OnDorm_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campus_NO", DbType="NVarChar(20)")]
		public string Campus_NO
		{
			get
			{
				return this._Campus_NO;
			}
			set
			{
				if ((this._Campus_NO != value))
				{
					this.OnCampus_NOChanging(value);
					this.SendPropertyChanging();
					this._Campus_NO = value;
					this.SendPropertyChanged("Campus_NO");
					this.OnCampus_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Bed_Type")]
	public partial class Fresh_Bed_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Bed_Type;
		
		private string _Type_Name;
		
		private string _FK_Room_Type;
		
		private string _Bed_Index;
		
		private string _Bed_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Bed_TypeChanging(string value);
    partial void OnPK_Bed_TypeChanged();
    partial void OnType_NameChanging(string value);
    partial void OnType_NameChanged();
    partial void OnFK_Room_TypeChanging(string value);
    partial void OnFK_Room_TypeChanged();
    partial void OnBed_IndexChanging(string value);
    partial void OnBed_IndexChanged();
    partial void OnBed_NOChanging(string value);
    partial void OnBed_NOChanged();
    #endregion
		
		public Fresh_Bed_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Bed_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Bed_Type
		{
			get
			{
				return this._PK_Bed_Type;
			}
			set
			{
				if ((this._PK_Bed_Type != value))
				{
					this.OnPK_Bed_TypeChanging(value);
					this.SendPropertyChanging();
					this._PK_Bed_Type = value;
					this.SendPropertyChanged("PK_Bed_Type");
					this.OnPK_Bed_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Name", DbType="NVarChar(50)")]
		public string Type_Name
		{
			get
			{
				return this._Type_Name;
			}
			set
			{
				if ((this._Type_Name != value))
				{
					this.OnType_NameChanging(value);
					this.SendPropertyChanging();
					this._Type_Name = value;
					this.SendPropertyChanged("Type_Name");
					this.OnType_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Room_Type", DbType="NVarChar(50)")]
		public string FK_Room_Type
		{
			get
			{
				return this._FK_Room_Type;
			}
			set
			{
				if ((this._FK_Room_Type != value))
				{
					this.OnFK_Room_TypeChanging(value);
					this.SendPropertyChanging();
					this._FK_Room_Type = value;
					this.SendPropertyChanged("FK_Room_Type");
					this.OnFK_Room_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bed_Index", DbType="NVarChar(20)")]
		public string Bed_Index
		{
			get
			{
				return this._Bed_Index;
			}
			set
			{
				if ((this._Bed_Index != value))
				{
					this.OnBed_IndexChanging(value);
					this.SendPropertyChanging();
					this._Bed_Index = value;
					this.SendPropertyChanged("Bed_Index");
					this.OnBed_IndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bed_NO", DbType="NVarChar(20)")]
		public string Bed_NO
		{
			get
			{
				return this._Bed_NO;
			}
			set
			{
				if ((this._Bed_NO != value))
				{
					this.OnBed_NOChanging(value);
					this.SendPropertyChanging();
					this._Bed_NO = value;
					this.SendPropertyChanged("Bed_NO");
					this.OnBed_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Bed")]
	public partial class Fresh_Bed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Bed_NO;
		
		private string _Bed_NO;
		
		private string _FK_Bed_Type;
		
		private string _FK_Room_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Bed_NOChanging(string value);
    partial void OnPK_Bed_NOChanged();
    partial void OnBed_NOChanging(string value);
    partial void OnBed_NOChanged();
    partial void OnFK_Bed_TypeChanging(string value);
    partial void OnFK_Bed_TypeChanged();
    partial void OnFK_Room_NOChanging(string value);
    partial void OnFK_Room_NOChanged();
    #endregion
		
		public Fresh_Bed()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Bed_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Bed_NO
		{
			get
			{
				return this._PK_Bed_NO;
			}
			set
			{
				if ((this._PK_Bed_NO != value))
				{
					this.OnPK_Bed_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Bed_NO = value;
					this.SendPropertyChanged("PK_Bed_NO");
					this.OnPK_Bed_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bed_NO", DbType="NVarChar(20)")]
		public string Bed_NO
		{
			get
			{
				return this._Bed_NO;
			}
			set
			{
				if ((this._Bed_NO != value))
				{
					this.OnBed_NOChanging(value);
					this.SendPropertyChanging();
					this._Bed_NO = value;
					this.SendPropertyChanged("Bed_NO");
					this.OnBed_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Bed_Type", DbType="NVarChar(50)")]
		public string FK_Bed_Type
		{
			get
			{
				return this._FK_Bed_Type;
			}
			set
			{
				if ((this._FK_Bed_Type != value))
				{
					this.OnFK_Bed_TypeChanging(value);
					this.SendPropertyChanging();
					this._FK_Bed_Type = value;
					this.SendPropertyChanged("FK_Bed_Type");
					this.OnFK_Bed_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Room_NO", DbType="NVarChar(50)")]
		public string FK_Room_NO
		{
			get
			{
				return this._FK_Room_NO;
			}
			set
			{
				if ((this._FK_Room_NO != value))
				{
					this.OnFK_Room_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Room_NO = value;
					this.SendPropertyChanged("FK_Room_NO");
					this.OnFK_Room_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Room_Type")]
	public partial class Fresh_Room_Type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Room_Type;
		
		private string _Type_NO;
		
		private string _Year;
		
		private string _Room_Layout;
		
		private string _Bed_Layout;
		
		private string _FK_Fee_Item;
		
		private string _Type_Name;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Room_TypeChanging(string value);
    partial void OnPK_Room_TypeChanged();
    partial void OnType_NOChanging(string value);
    partial void OnType_NOChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnRoom_LayoutChanging(string value);
    partial void OnRoom_LayoutChanged();
    partial void OnBed_LayoutChanging(string value);
    partial void OnBed_LayoutChanged();
    partial void OnFK_Fee_ItemChanging(string value);
    partial void OnFK_Fee_ItemChanged();
    partial void OnType_NameChanging(string value);
    partial void OnType_NameChanged();
    #endregion
		
		public Fresh_Room_Type()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Room_Type", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Room_Type
		{
			get
			{
				return this._PK_Room_Type;
			}
			set
			{
				if ((this._PK_Room_Type != value))
				{
					this.OnPK_Room_TypeChanging(value);
					this.SendPropertyChanging();
					this._PK_Room_Type = value;
					this.SendPropertyChanged("PK_Room_Type");
					this.OnPK_Room_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_NO", DbType="NVarChar(20)")]
		public string Type_NO
		{
			get
			{
				return this._Type_NO;
			}
			set
			{
				if ((this._Type_NO != value))
				{
					this.OnType_NOChanging(value);
					this.SendPropertyChanging();
					this._Type_NO = value;
					this.SendPropertyChanged("Type_NO");
					this.OnType_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Layout", DbType="NVarChar(255)")]
		public string Room_Layout
		{
			get
			{
				return this._Room_Layout;
			}
			set
			{
				if ((this._Room_Layout != value))
				{
					this.OnRoom_LayoutChanging(value);
					this.SendPropertyChanging();
					this._Room_Layout = value;
					this.SendPropertyChanged("Room_Layout");
					this.OnRoom_LayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bed_Layout", DbType="NVarChar(255)")]
		public string Bed_Layout
		{
			get
			{
				return this._Bed_Layout;
			}
			set
			{
				if ((this._Bed_Layout != value))
				{
					this.OnBed_LayoutChanging(value);
					this.SendPropertyChanging();
					this._Bed_Layout = value;
					this.SendPropertyChanged("Bed_Layout");
					this.OnBed_LayoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Fee_Item", DbType="NVarChar(50)")]
		public string FK_Fee_Item
		{
			get
			{
				return this._FK_Fee_Item;
			}
			set
			{
				if ((this._FK_Fee_Item != value))
				{
					this.OnFK_Fee_ItemChanging(value);
					this.SendPropertyChanging();
					this._FK_Fee_Item = value;
					this.SendPropertyChanged("FK_Fee_Item");
					this.OnFK_Fee_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Name", DbType="NVarChar(50)")]
		public string Type_Name
		{
			get
			{
				return this._Type_Name;
			}
			set
			{
				if ((this._Type_Name != value))
				{
					this.OnType_NameChanging(value);
					this.SendPropertyChanging();
					this._Type_Name = value;
					this.SendPropertyChanged("Type_Name");
					this.OnType_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
