<?xml version="1.0" encoding="utf-8"?><Database Name="yxxt_data" Class="dormitoryModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=118.114.252.173,20933;Initial Catalog=yxxt_data;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="yxxt_dataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fresh_Bed_Log" Member="Fresh_Bed_Logs">
    <Type Name="Fresh_Bed_Log">
      <Column Name="PK_Bed_Log" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Bed_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_SNO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Updater" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Update_DT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>