#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yxxt_data")]
	public partial class messageModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertClassMsg(ClassMsg instance);
    partial void UpdateClassMsg(ClassMsg instance);
    partial void DeleteClassMsg(ClassMsg instance);
    partial void InsertClassMsgObj(ClassMsgObj instance);
    partial void UpdateClassMsgObj(ClassMsgObj instance);
    partial void DeleteClassMsgObj(ClassMsgObj instance);
    partial void InsertClassMsgStu(ClassMsgStu instance);
    partial void UpdateClassMsgStu(ClassMsgStu instance);
    partial void DeleteClassMsgStu(ClassMsgStu instance);
    #endregion
		
		public messageModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yxxt_dataConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public messageModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public messageModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public messageModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public messageModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClassMsg> ClassMsgs
		{
			get
			{
				return this.GetTable<ClassMsg>();
			}
		}
		
		public System.Data.Linq.Table<ClassMsgObj> ClassMsgObjs
		{
			get
			{
				return this.GetTable<ClassMsgObj>();
			}
		}
		
		public System.Data.Linq.Table<ClassMsgStu> ClassMsgStus
		{
			get
			{
				return this.GetTable<ClassMsgStu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassMsg")]
	public partial class ClassMsg : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PK_NO;
		
		private string _Title;
		
		private string _Content;
		
		private System.DateTime _CreateDate;
		
		private string _Author;
		
		private string _Disabled;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_NOChanging(long value);
    partial void OnPK_NOChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnContentChanging(string value);
    partial void OnContentChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnAuthorChanging(string value);
    partial void OnAuthorChanged();
    partial void OnDisabledChanging(string value);
    partial void OnDisabledChanged();
    #endregion
		
		public ClassMsg()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_NO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PK_NO
		{
			get
			{
				return this._PK_NO;
			}
			set
			{
				if ((this._PK_NO != value))
				{
					this.OnPK_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_NO = value;
					this.SendPropertyChanged("PK_NO");
					this.OnPK_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Content", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Content
		{
			get
			{
				return this._Content;
			}
			set
			{
				if ((this._Content != value))
				{
					this.OnContentChanging(value);
					this.SendPropertyChanging();
					this._Content = value;
					this.SendPropertyChanged("Content");
					this.OnContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Author", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Author
		{
			get
			{
				return this._Author;
			}
			set
			{
				if ((this._Author != value))
				{
					this.OnAuthorChanging(value);
					this.SendPropertyChanging();
					this._Author = value;
					this.SendPropertyChanged("Author");
					this.OnAuthorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassMsgObj")]
	public partial class ClassMsgObj : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PK_NO;
		
		private long _FK_NO_ClassMsg;
		
		private string _FK_Class_NO;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_NOChanging(long value);
    partial void OnPK_NOChanged();
    partial void OnFK_NO_ClassMsgChanging(long value);
    partial void OnFK_NO_ClassMsgChanged();
    partial void OnFK_Class_NOChanging(string value);
    partial void OnFK_Class_NOChanged();
    #endregion
		
		public ClassMsgObj()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_NO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PK_NO
		{
			get
			{
				return this._PK_NO;
			}
			set
			{
				if ((this._PK_NO != value))
				{
					this.OnPK_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_NO = value;
					this.SendPropertyChanged("PK_NO");
					this.OnPK_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_NO_ClassMsg", DbType="BigInt NOT NULL")]
		public long FK_NO_ClassMsg
		{
			get
			{
				return this._FK_NO_ClassMsg;
			}
			set
			{
				if ((this._FK_NO_ClassMsg != value))
				{
					this.OnFK_NO_ClassMsgChanging(value);
					this.SendPropertyChanging();
					this._FK_NO_ClassMsg = value;
					this.SendPropertyChanged("FK_NO_ClassMsg");
					this.OnFK_NO_ClassMsgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Class_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FK_Class_NO
		{
			get
			{
				return this._FK_Class_NO;
			}
			set
			{
				if ((this._FK_Class_NO != value))
				{
					this.OnFK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Class_NO = value;
					this.SendPropertyChanged("FK_Class_NO");
					this.OnFK_Class_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClassMsgStu")]
	public partial class ClassMsgStu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _PK_NO;
		
		private string _FK_SNO;
		
		private System.DateTime _ReadDate;
		
		private long _FK_NO_ClassMsg;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_NOChanging(long value);
    partial void OnPK_NOChanged();
    partial void OnFK_SNOChanging(string value);
    partial void OnFK_SNOChanged();
    partial void OnReadDateChanging(System.DateTime value);
    partial void OnReadDateChanged();
    partial void OnFK_NO_ClassMsgChanging(long value);
    partial void OnFK_NO_ClassMsgChanged();
    #endregion
		
		public ClassMsgStu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_NO", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long PK_NO
		{
			get
			{
				return this._PK_NO;
			}
			set
			{
				if ((this._PK_NO != value))
				{
					this.OnPK_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_NO = value;
					this.SendPropertyChanged("PK_NO");
					this.OnPK_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string FK_SNO
		{
			get
			{
				return this._FK_SNO;
			}
			set
			{
				if ((this._FK_SNO != value))
				{
					this.OnFK_SNOChanging(value);
					this.SendPropertyChanging();
					this._FK_SNO = value;
					this.SendPropertyChanged("FK_SNO");
					this.OnFK_SNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReadDate", DbType="DateTime NOT NULL")]
		public System.DateTime ReadDate
		{
			get
			{
				return this._ReadDate;
			}
			set
			{
				if ((this._ReadDate != value))
				{
					this.OnReadDateChanging(value);
					this.SendPropertyChanging();
					this._ReadDate = value;
					this.SendPropertyChanged("ReadDate");
					this.OnReadDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_NO_ClassMsg", DbType="BigInt NOT NULL")]
		public long FK_NO_ClassMsg
		{
			get
			{
				return this._FK_NO_ClassMsg;
			}
			set
			{
				if ((this._FK_NO_ClassMsg != value))
				{
					this.OnFK_NO_ClassMsgChanging(value);
					this.SendPropertyChanging();
					this._FK_NO_ClassMsg = value;
					this.SendPropertyChanged("FK_NO_ClassMsg");
					this.OnFK_NO_ClassMsgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
