#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36366
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yxxt_data")]
	public partial class organizationModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBase_Staff(Base_Staff instance);
    partial void UpdateBase_Staff(Base_Staff instance);
    partial void DeleteBase_Staff(Base_Staff instance);
    partial void InsertFresh_SPE(Fresh_SPE instance);
    partial void UpdateFresh_SPE(Fresh_SPE instance);
    partial void DeleteFresh_SPE(Fresh_SPE instance);
    partial void InsertFresh_Class(Fresh_Class instance);
    partial void UpdateFresh_Class(Fresh_Class instance);
    partial void DeleteFresh_Class(Fresh_Class instance);
    partial void InsertBase_STU(Base_STU instance);
    partial void UpdateBase_STU(Base_STU instance);
    partial void DeleteBase_STU(Base_STU instance);
    #endregion
		
		public organizationModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yxxt_dataConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Base_Staff> Base_Staffs
		{
			get
			{
				return this.GetTable<Base_Staff>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_SPE> Fresh_SPEs
		{
			get
			{
				return this.GetTable<Fresh_SPE>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Class> Fresh_Classes
		{
			get
			{
				return this.GetTable<Fresh_Class>();
			}
		}
		
		public System.Data.Linq.Table<Base_STU> Base_STUs
		{
			get
			{
				return this.GetTable<Base_STU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_Staff")]
	public partial class Base_Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Staff_NO;
		
		private string _Phone;
		
		private string _FK_College_NO;
		
		private string _Name;
		
		private string _Gender;
		
		private string _Password;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Staff_NOChanging(string value);
    partial void OnPK_Staff_NOChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFK_College_NOChanging(string value);
    partial void OnFK_College_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Base_Staff()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Staff_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Staff_NO
		{
			get
			{
				return this._PK_Staff_NO;
			}
			set
			{
				if ((this._PK_Staff_NO != value))
				{
					this.OnPK_Staff_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Staff_NO = value;
					this.SendPropertyChanged("PK_Staff_NO");
					this.OnPK_Staff_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_College_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FK_College_NO
		{
			get
			{
				return this._FK_College_NO;
			}
			set
			{
				if ((this._FK_College_NO != value))
				{
					this.OnFK_College_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_College_NO = value;
					this.SendPropertyChanged("FK_College_NO");
					this.OnFK_College_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_SPE")]
	public partial class Fresh_SPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SPE_Code;
		
		private string _Year;
		
		private string _SPE_Name;
		
		private string _EDU_Level_Code;
		
		private string _FK_College_Code;
		
		private string _PK_SPE;
		
		private EntitySet<Fresh_Class> _Fresh_Classes;
		
		private EntitySet<Base_STU> _Base_STUs;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSPE_CodeChanging(string value);
    partial void OnSPE_CodeChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnSPE_NameChanging(string value);
    partial void OnSPE_NameChanged();
    partial void OnEDU_Level_CodeChanging(string value);
    partial void OnEDU_Level_CodeChanged();
    partial void OnFK_College_CodeChanging(string value);
    partial void OnFK_College_CodeChanged();
    partial void OnPK_SPEChanging(string value);
    partial void OnPK_SPEChanged();
    #endregion
		
		public Fresh_SPE()
		{
			this._Fresh_Classes = new EntitySet<Fresh_Class>(new Action<Fresh_Class>(this.attach_Fresh_Classes), new Action<Fresh_Class>(this.detach_Fresh_Classes));
			this._Base_STUs = new EntitySet<Base_STU>(new Action<Base_STU>(this.attach_Base_STUs), new Action<Base_STU>(this.detach_Base_STUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPE_Code", DbType="NVarChar(50)")]
		public string SPE_Code
		{
			get
			{
				return this._SPE_Code;
			}
			set
			{
				if ((this._SPE_Code != value))
				{
					this.OnSPE_CodeChanging(value);
					this.SendPropertyChanging();
					this._SPE_Code = value;
					this.SendPropertyChanged("SPE_Code");
					this.OnSPE_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPE_Name", DbType="NVarChar(50)")]
		public string SPE_Name
		{
			get
			{
				return this._SPE_Name;
			}
			set
			{
				if ((this._SPE_Name != value))
				{
					this.OnSPE_NameChanging(value);
					this.SendPropertyChanging();
					this._SPE_Name = value;
					this.SendPropertyChanged("SPE_Name");
					this.OnSPE_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDU_Level_Code", DbType="NVarChar(20)")]
		public string EDU_Level_Code
		{
			get
			{
				return this._EDU_Level_Code;
			}
			set
			{
				if ((this._EDU_Level_Code != value))
				{
					this.OnEDU_Level_CodeChanging(value);
					this.SendPropertyChanging();
					this._EDU_Level_Code = value;
					this.SendPropertyChanged("EDU_Level_Code");
					this.OnEDU_Level_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_College_Code", DbType="NVarChar(50)")]
		public string FK_College_Code
		{
			get
			{
				return this._FK_College_Code;
			}
			set
			{
				if ((this._FK_College_Code != value))
				{
					this.OnFK_College_CodeChanging(value);
					this.SendPropertyChanging();
					this._FK_College_Code = value;
					this.SendPropertyChanged("FK_College_Code");
					this.OnFK_College_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_SPE
		{
			get
			{
				return this._PK_SPE;
			}
			set
			{
				if ((this._PK_SPE != value))
				{
					this.OnPK_SPEChanging(value);
					this.SendPropertyChanging();
					this._PK_SPE = value;
					this.SendPropertyChanged("PK_SPE");
					this.OnPK_SPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Fresh_Class", Storage="_Fresh_Classes", ThisKey="PK_SPE", OtherKey="FK_SPE_NO")]
		public EntitySet<Fresh_Class> Fresh_Classes
		{
			get
			{
				return this._Fresh_Classes;
			}
			set
			{
				this._Fresh_Classes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Base_STU", Storage="_Base_STUs", ThisKey="PK_SPE", OtherKey="FK_SPE_Code")]
		public EntitySet<Base_STU> Base_STUs
		{
			get
			{
				return this._Base_STUs;
			}
			set
			{
				this._Base_STUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = this;
		}
		
		private void detach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = null;
		}
		
		private void attach_Base_STUs(Base_STU entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = this;
		}
		
		private void detach_Base_STUs(Base_STU entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Class")]
	public partial class Fresh_Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Class_NO;
		
		private string _FK_Campus_NO;
		
		private string _FK_SPE_NO;
		
		private string _Name;
		
		private EntityRef<Fresh_SPE> _Fresh_SPE;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Class_NOChanging(string value);
    partial void OnPK_Class_NOChanged();
    partial void OnFK_Campus_NOChanging(string value);
    partial void OnFK_Campus_NOChanged();
    partial void OnFK_SPE_NOChanging(string value);
    partial void OnFK_SPE_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Fresh_Class()
		{
			this._Fresh_SPE = default(EntityRef<Fresh_SPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Class_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Class_NO
		{
			get
			{
				return this._PK_Class_NO;
			}
			set
			{
				if ((this._PK_Class_NO != value))
				{
					this.OnPK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Class_NO = value;
					this.SendPropertyChanged("PK_Class_NO");
					this.OnPK_Class_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Campus_NO", DbType="NVarChar(50)")]
		public string FK_Campus_NO
		{
			get
			{
				return this._FK_Campus_NO;
			}
			set
			{
				if ((this._FK_Campus_NO != value))
				{
					this.OnFK_Campus_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Campus_NO = value;
					this.SendPropertyChanged("FK_Campus_NO");
					this.OnFK_Campus_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SPE_NO", DbType="NVarChar(50)")]
		public string FK_SPE_NO
		{
			get
			{
				return this._FK_SPE_NO;
			}
			set
			{
				if ((this._FK_SPE_NO != value))
				{
					if (this._Fresh_SPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SPE_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_SPE_NO = value;
					this.SendPropertyChanged("FK_SPE_NO");
					this.OnFK_SPE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Fresh_Class", Storage="_Fresh_SPE", ThisKey="FK_SPE_NO", OtherKey="PK_SPE", IsForeignKey=true)]
		public Fresh_SPE Fresh_SPE
		{
			get
			{
				return this._Fresh_SPE.Entity;
			}
			set
			{
				Fresh_SPE previousValue = this._Fresh_SPE.Entity;
				if (((previousValue != value) 
							|| (this._Fresh_SPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fresh_SPE.Entity = null;
						previousValue.Fresh_Classes.Remove(this);
					}
					this._Fresh_SPE.Entity = value;
					if ((value != null))
					{
						value.Fresh_Classes.Add(this);
						this._FK_SPE_NO = value.PK_SPE;
					}
					else
					{
						this._FK_SPE_NO = default(string);
					}
					this.SendPropertyChanged("Fresh_SPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_STU")]
	public partial class Base_STU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_SNO;
		
		private string _FK_SPE_Code;
		
		private string _Year;
		
		private string _Test_NO;
		
		private string _ID_NO;
		
		private string _Name;
		
		private string _Gender_Code;
		
		private string _Photo;
		
		private string _Status_Code;
		
		private System.Nullable<System.DateTime> _DT_Initial;
		
		private string _FK_Class_NO;
		
		private string _Password;
		
		private EntityRef<Fresh_SPE> _Fresh_SPE;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_SNOChanging(string value);
    partial void OnPK_SNOChanged();
    partial void OnFK_SPE_CodeChanging(string value);
    partial void OnFK_SPE_CodeChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnTest_NOChanging(string value);
    partial void OnTest_NOChanged();
    partial void OnID_NOChanging(string value);
    partial void OnID_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGender_CodeChanging(string value);
    partial void OnGender_CodeChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnStatus_CodeChanging(string value);
    partial void OnStatus_CodeChanged();
    partial void OnDT_InitialChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_InitialChanged();
    partial void OnFK_Class_NOChanging(string value);
    partial void OnFK_Class_NOChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Base_STU()
		{
			this._Fresh_SPE = default(EntityRef<Fresh_SPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_SNO
		{
			get
			{
				return this._PK_SNO;
			}
			set
			{
				if ((this._PK_SNO != value))
				{
					this.OnPK_SNOChanging(value);
					this.SendPropertyChanging();
					this._PK_SNO = value;
					this.SendPropertyChanged("PK_SNO");
					this.OnPK_SNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SPE_Code", DbType="NVarChar(50)")]
		public string FK_SPE_Code
		{
			get
			{
				return this._FK_SPE_Code;
			}
			set
			{
				if ((this._FK_SPE_Code != value))
				{
					if (this._Fresh_SPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SPE_CodeChanging(value);
					this.SendPropertyChanging();
					this._FK_SPE_Code = value;
					this.SendPropertyChanged("FK_SPE_Code");
					this.OnFK_SPE_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(10)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_NO", DbType="NVarChar(20)")]
		public string Test_NO
		{
			get
			{
				return this._Test_NO;
			}
			set
			{
				if ((this._Test_NO != value))
				{
					this.OnTest_NOChanging(value);
					this.SendPropertyChanging();
					this._Test_NO = value;
					this.SendPropertyChanged("Test_NO");
					this.OnTest_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NO", DbType="NVarChar(20)")]
		public string ID_NO
		{
			get
			{
				return this._ID_NO;
			}
			set
			{
				if ((this._ID_NO != value))
				{
					this.OnID_NOChanging(value);
					this.SendPropertyChanging();
					this._ID_NO = value;
					this.SendPropertyChanged("ID_NO");
					this.OnID_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender_Code", DbType="NVarChar(10)")]
		public string Gender_Code
		{
			get
			{
				return this._Gender_Code;
			}
			set
			{
				if ((this._Gender_Code != value))
				{
					this.OnGender_CodeChanging(value);
					this.SendPropertyChanging();
					this._Gender_Code = value;
					this.SendPropertyChanged("Gender_Code");
					this.OnGender_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(255)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Code", DbType="NVarChar(10)")]
		public string Status_Code
		{
			get
			{
				return this._Status_Code;
			}
			set
			{
				if ((this._Status_Code != value))
				{
					this.OnStatus_CodeChanging(value);
					this.SendPropertyChanging();
					this._Status_Code = value;
					this.SendPropertyChanged("Status_Code");
					this.OnStatus_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Initial", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Initial
		{
			get
			{
				return this._DT_Initial;
			}
			set
			{
				if ((this._DT_Initial != value))
				{
					this.OnDT_InitialChanging(value);
					this.SendPropertyChanging();
					this._DT_Initial = value;
					this.SendPropertyChanged("DT_Initial");
					this.OnDT_InitialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Class_NO", DbType="NVarChar(50)")]
		public string FK_Class_NO
		{
			get
			{
				return this._FK_Class_NO;
			}
			set
			{
				if ((this._FK_Class_NO != value))
				{
					this.OnFK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Class_NO = value;
					this.SendPropertyChanged("FK_Class_NO");
					this.OnFK_Class_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Base_STU", Storage="_Fresh_SPE", ThisKey="FK_SPE_Code", OtherKey="PK_SPE", IsForeignKey=true)]
		public Fresh_SPE Fresh_SPE
		{
			get
			{
				return this._Fresh_SPE.Entity;
			}
			set
			{
				Fresh_SPE previousValue = this._Fresh_SPE.Entity;
				if (((previousValue != value) 
							|| (this._Fresh_SPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fresh_SPE.Entity = null;
						previousValue.Base_STUs.Remove(this);
					}
					this._Fresh_SPE.Entity = value;
					if ((value != null))
					{
						value.Base_STUs.Add(this);
						this._FK_SPE_Code = value.PK_SPE;
					}
					else
					{
						this._FK_SPE_Code = default(string);
					}
					this.SendPropertyChanged("Fresh_SPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
