<?xml version="1.0" encoding="utf-8"?><Database Name="yxxt_data" Class="organizationModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=118.114.252.173,20933;Initial Catalog=yxxt_data;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="yxxt_dataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Base_Staff" Member="Base_Staffs">
    <Type Name="Base_Staff">
      <Column Name="PK_Staff_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FK_College_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Base_Staff_Fresh_Counseller" Member="Fresh_Counsellers" ThisKey="PK_Staff_NO" OtherKey="FK_Staff_NO" Type="Fresh_Counseller" />
      <Association Name="Base_College_Base_Staff" Member="Base_College" AccessModifier="Internal" ThisKey="FK_College_NO" OtherKey="PK_College" Type="Base_College" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_SPE" Member="Fresh_SPEs">
    <Type Name="Fresh_SPE">
      <Column Name="SPE_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SPE_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDU_Level_Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FK_College_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PK_SPE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Fresh_SPE_Fresh_Class" Member="Fresh_Classes" ThisKey="PK_SPE" OtherKey="FK_SPE_NO" Type="Fresh_Class" />
      <Association Name="Fresh_SPE_Base_STU" Member="Base_STUs" ThisKey="PK_SPE" OtherKey="FK_SPE_Code" Type="Base_STU" />
      <Association Name="Base_College_Fresh_SPE" Member="Base_College" AccessModifier="Internal" ThisKey="FK_College_Code" OtherKey="PK_College" Type="Base_College" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_Class" Member="Fresh_Classes">
    <Type Name="Fresh_Class">
      <Column Name="PK_Class_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Campus_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_SPE_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Fresh_Class_Fresh_Counseller" Member="Fresh_Counsellers" ThisKey="PK_Class_NO" OtherKey="FK_Class_NO" Type="Fresh_Counseller" />
      <Association Name="Fresh_SPE_Fresh_Class" Member="Fresh_SPE" AccessModifier="Internal" ThisKey="FK_SPE_NO" OtherKey="PK_SPE" Type="Fresh_SPE" IsForeignKey="true" />
      <Association Name="Base_Campus_Fresh_Class" Member="Base_Campus" AccessModifier="Internal" ThisKey="FK_Campus_NO" OtherKey="PK_Campus" Type="Base_Campus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Base_STU" Member="Base_STUs">
    <Type Name="Base_STU">
      <Column Name="PK_SNO" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_SPE_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Test_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ID_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Gender_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DT_Initial" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_Class_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Base_STU_Fresh_STU" Member="Fresh_STU" ThisKey="PK_SNO" OtherKey="PK_SNO" Type="Fresh_STU" Cardinality="One" />
      <Association Name="Fresh_SPE_Base_STU" Member="Fresh_SPE" AccessModifier="Internal" ThisKey="FK_SPE_Code" OtherKey="PK_SPE" Type="Fresh_SPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_STU" Member="Fresh_STUs">
    <Type Name="Fresh_STU">
      <Column Name="PK_SNO" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Fresh_Batch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FK_Class_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Base_STU_Fresh_STU" Member="Base_STU" AccessModifier="Internal" ThisKey="PK_SNO" OtherKey="PK_SNO" Type="Base_STU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Base_College" Member="Base_Colleges">
    <Type Name="Base_College">
      <Column Name="PK_College" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="College_NO" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Base_College_Base_Staff" Member="Base_Staffs" ThisKey="PK_College" OtherKey="FK_College_NO" Type="Base_Staff" />
      <Association Name="Base_College_Fresh_SPE" Member="Fresh_SPEs" ThisKey="PK_College" OtherKey="FK_College_Code" Type="Fresh_SPE" />
    </Type>
  </Table>
  <Table Name="dbo.Base_Campus" Member="Base_Campus">
    <Type Name="Base_Campus">
      <Column Name="PK_Campus" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Campus_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Campus_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="Base_Campus_Fresh_Class" Member="Fresh_Classes" ThisKey="PK_Campus" OtherKey="FK_Campus_NO" Type="Fresh_Class" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_Counseller" Member="Fresh_Counsellers">
    <Type Name="Fresh_Counseller">
      <Column Name="PK_Counseller_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Class_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_Staff_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Fresh_Class_Fresh_Counseller" Member="Fresh_Class" AccessModifier="Internal" ThisKey="FK_Class_NO" OtherKey="PK_Class_NO" Type="Fresh_Class" IsForeignKey="true" />
      <Association Name="Base_Staff_Fresh_Counseller" Member="Base_Staff" AccessModifier="Internal" ThisKey="FK_Staff_NO" OtherKey="PK_Staff_NO" Type="Base_Staff" IsForeignKey="true" />
    </Type>
  </Table>
</Database>