#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="yxxt_data")]
	public partial class organizationModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertBase_Staff(Base_Staff instance);
    partial void UpdateBase_Staff(Base_Staff instance);
    partial void DeleteBase_Staff(Base_Staff instance);
    partial void InsertFresh_SPE(Fresh_SPE instance);
    partial void UpdateFresh_SPE(Fresh_SPE instance);
    partial void DeleteFresh_SPE(Fresh_SPE instance);
    partial void InsertFresh_Class(Fresh_Class instance);
    partial void UpdateFresh_Class(Fresh_Class instance);
    partial void DeleteFresh_Class(Fresh_Class instance);
    partial void InsertBase_College(Base_College instance);
    partial void UpdateBase_College(Base_College instance);
    partial void DeleteBase_College(Base_College instance);
    partial void InsertBase_Campus(Base_Campus instance);
    partial void UpdateBase_Campus(Base_Campus instance);
    partial void DeleteBase_Campus(Base_Campus instance);
    partial void InsertFresh_Counseller(Fresh_Counseller instance);
    partial void UpdateFresh_Counseller(Fresh_Counseller instance);
    partial void DeleteFresh_Counseller(Fresh_Counseller instance);
    partial void InsertBase_STU(Base_STU instance);
    partial void UpdateBase_STU(Base_STU instance);
    partial void DeleteBase_STU(Base_STU instance);
    #endregion
		
		public organizationModelDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["yxxt_dataConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public organizationModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Base_Staff> Base_Staffs
		{
			get
			{
				return this.GetTable<Base_Staff>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_SPE> Fresh_SPEs
		{
			get
			{
				return this.GetTable<Fresh_SPE>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Class> Fresh_Classes
		{
			get
			{
				return this.GetTable<Fresh_Class>();
			}
		}
		
		public System.Data.Linq.Table<Base_College> Base_Colleges
		{
			get
			{
				return this.GetTable<Base_College>();
			}
		}
		
		public System.Data.Linq.Table<Base_Campus> Base_Campus
		{
			get
			{
				return this.GetTable<Base_Campus>();
			}
		}
		
		public System.Data.Linq.Table<Fresh_Counseller> Fresh_Counsellers
		{
			get
			{
				return this.GetTable<Fresh_Counseller>();
			}
		}
		
		public System.Data.Linq.Table<Base_STU> Base_STUs
		{
			get
			{
				return this.GetTable<Base_STU>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_Staff")]
	public partial class Base_Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Staff_NO;
		
		private string _Phone;
		
		private string _FK_College_NO;
		
		private string _Name;
		
		private string _Gender;
		
		private string _Password;
		
		private EntitySet<Fresh_Counseller> _Fresh_Counsellers;
		
		private EntityRef<Base_College> _Base_College;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Staff_NOChanging(string value);
    partial void OnPK_Staff_NOChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFK_College_NOChanging(string value);
    partial void OnFK_College_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Base_Staff()
		{
			this._Fresh_Counsellers = new EntitySet<Fresh_Counseller>(new Action<Fresh_Counseller>(this.attach_Fresh_Counsellers), new Action<Fresh_Counseller>(this.detach_Fresh_Counsellers));
			this._Base_College = default(EntityRef<Base_College>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Staff_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Staff_NO
		{
			get
			{
				return this._PK_Staff_NO;
			}
			set
			{
				if ((this._PK_Staff_NO != value))
				{
					this.OnPK_Staff_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Staff_NO = value;
					this.SendPropertyChanged("PK_Staff_NO");
					this.OnPK_Staff_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_College_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FK_College_NO
		{
			get
			{
				return this._FK_College_NO;
			}
			set
			{
				if ((this._FK_College_NO != value))
				{
					if (this._Base_College.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_College_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_College_NO = value;
					this.SendPropertyChanged("FK_College_NO");
					this.OnFK_College_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_Staff_Fresh_Counseller", Storage="_Fresh_Counsellers", ThisKey="PK_Staff_NO", OtherKey="FK_Staff_NO")]
		public EntitySet<Fresh_Counseller> Fresh_Counsellers
		{
			get
			{
				return this._Fresh_Counsellers;
			}
			set
			{
				this._Fresh_Counsellers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_College_Base_Staff", Storage="_Base_College", ThisKey="FK_College_NO", OtherKey="PK_College", IsForeignKey=true)]
		internal Base_College Base_College
		{
			get
			{
				return this._Base_College.Entity;
			}
			set
			{
				Base_College previousValue = this._Base_College.Entity;
				if (((previousValue != value) 
							|| (this._Base_College.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Base_College.Entity = null;
						previousValue.Base_Staffs.Remove(this);
					}
					this._Base_College.Entity = value;
					if ((value != null))
					{
						value.Base_Staffs.Add(this);
						this._FK_College_NO = value.PK_College;
					}
					else
					{
						this._FK_College_NO = default(string);
					}
					this.SendPropertyChanged("Base_College");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fresh_Counsellers(Fresh_Counseller entity)
		{
			this.SendPropertyChanging();
			entity.Base_Staff = this;
		}
		
		private void detach_Fresh_Counsellers(Fresh_Counseller entity)
		{
			this.SendPropertyChanging();
			entity.Base_Staff = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_SPE")]
	public partial class Fresh_SPE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SPE_Code;
		
		private string _Year;
		
		private string _SPE_Name;
		
		private string _EDU_Level_Code;
		
		private string _FK_College_Code;
		
		private string _PK_SPE;
		
		private EntitySet<Fresh_Class> _Fresh_Classes;
		
		private EntitySet<Base_STU> _Base_STUs;
		
		private EntityRef<Base_College> _Base_College;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSPE_CodeChanging(string value);
    partial void OnSPE_CodeChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnSPE_NameChanging(string value);
    partial void OnSPE_NameChanged();
    partial void OnEDU_Level_CodeChanging(string value);
    partial void OnEDU_Level_CodeChanged();
    partial void OnFK_College_CodeChanging(string value);
    partial void OnFK_College_CodeChanged();
    partial void OnPK_SPEChanging(string value);
    partial void OnPK_SPEChanged();
    #endregion
		
		public Fresh_SPE()
		{
			this._Fresh_Classes = new EntitySet<Fresh_Class>(new Action<Fresh_Class>(this.attach_Fresh_Classes), new Action<Fresh_Class>(this.detach_Fresh_Classes));
			this._Base_STUs = new EntitySet<Base_STU>(new Action<Base_STU>(this.attach_Base_STUs), new Action<Base_STU>(this.detach_Base_STUs));
			this._Base_College = default(EntityRef<Base_College>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPE_Code", DbType="NVarChar(50)")]
		public string SPE_Code
		{
			get
			{
				return this._SPE_Code;
			}
			set
			{
				if ((this._SPE_Code != value))
				{
					this.OnSPE_CodeChanging(value);
					this.SendPropertyChanging();
					this._SPE_Code = value;
					this.SendPropertyChanged("SPE_Code");
					this.OnSPE_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SPE_Name", DbType="NVarChar(50)")]
		public string SPE_Name
		{
			get
			{
				return this._SPE_Name;
			}
			set
			{
				if ((this._SPE_Name != value))
				{
					this.OnSPE_NameChanging(value);
					this.SendPropertyChanging();
					this._SPE_Name = value;
					this.SendPropertyChanged("SPE_Name");
					this.OnSPE_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDU_Level_Code", DbType="NVarChar(20)")]
		public string EDU_Level_Code
		{
			get
			{
				return this._EDU_Level_Code;
			}
			set
			{
				if ((this._EDU_Level_Code != value))
				{
					this.OnEDU_Level_CodeChanging(value);
					this.SendPropertyChanging();
					this._EDU_Level_Code = value;
					this.SendPropertyChanged("EDU_Level_Code");
					this.OnEDU_Level_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_College_Code", DbType="NVarChar(50)")]
		public string FK_College_Code
		{
			get
			{
				return this._FK_College_Code;
			}
			set
			{
				if ((this._FK_College_Code != value))
				{
					if (this._Base_College.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_College_CodeChanging(value);
					this.SendPropertyChanging();
					this._FK_College_Code = value;
					this.SendPropertyChanged("FK_College_Code");
					this.OnFK_College_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SPE", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_SPE
		{
			get
			{
				return this._PK_SPE;
			}
			set
			{
				if ((this._PK_SPE != value))
				{
					this.OnPK_SPEChanging(value);
					this.SendPropertyChanging();
					this._PK_SPE = value;
					this.SendPropertyChanged("PK_SPE");
					this.OnPK_SPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Fresh_Class", Storage="_Fresh_Classes", ThisKey="PK_SPE", OtherKey="FK_SPE_NO")]
		public EntitySet<Fresh_Class> Fresh_Classes
		{
			get
			{
				return this._Fresh_Classes;
			}
			set
			{
				this._Fresh_Classes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Base_STU", Storage="_Base_STUs", ThisKey="PK_SPE", OtherKey="FK_SPE_Code")]
		public EntitySet<Base_STU> Base_STUs
		{
			get
			{
				return this._Base_STUs;
			}
			set
			{
				this._Base_STUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_College_Fresh_SPE", Storage="_Base_College", ThisKey="FK_College_Code", OtherKey="PK_College", IsForeignKey=true)]
		internal Base_College Base_College
		{
			get
			{
				return this._Base_College.Entity;
			}
			set
			{
				Base_College previousValue = this._Base_College.Entity;
				if (((previousValue != value) 
							|| (this._Base_College.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Base_College.Entity = null;
						previousValue.Fresh_SPEs.Remove(this);
					}
					this._Base_College.Entity = value;
					if ((value != null))
					{
						value.Fresh_SPEs.Add(this);
						this._FK_College_Code = value.PK_College;
					}
					else
					{
						this._FK_College_Code = default(string);
					}
					this.SendPropertyChanged("Base_College");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = this;
		}
		
		private void detach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = null;
		}
		
		private void attach_Base_STUs(Base_STU entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = this;
		}
		
		private void detach_Base_STUs(Base_STU entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_SPE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Class")]
	public partial class Fresh_Class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Class_NO;
		
		private string _FK_Campus_NO;
		
		private string _FK_SPE_NO;
		
		private string _Name;
		
		private EntitySet<Fresh_Counseller> _Fresh_Counsellers;
		
		private EntityRef<Fresh_SPE> _Fresh_SPE;
		
		private EntityRef<Base_Campus> _Base_Campus;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Class_NOChanging(string value);
    partial void OnPK_Class_NOChanged();
    partial void OnFK_Campus_NOChanging(string value);
    partial void OnFK_Campus_NOChanged();
    partial void OnFK_SPE_NOChanging(string value);
    partial void OnFK_SPE_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Fresh_Class()
		{
			this._Fresh_Counsellers = new EntitySet<Fresh_Counseller>(new Action<Fresh_Counseller>(this.attach_Fresh_Counsellers), new Action<Fresh_Counseller>(this.detach_Fresh_Counsellers));
			this._Fresh_SPE = default(EntityRef<Fresh_SPE>);
			this._Base_Campus = default(EntityRef<Base_Campus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Class_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Class_NO
		{
			get
			{
				return this._PK_Class_NO;
			}
			set
			{
				if ((this._PK_Class_NO != value))
				{
					this.OnPK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Class_NO = value;
					this.SendPropertyChanged("PK_Class_NO");
					this.OnPK_Class_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Campus_NO", DbType="NVarChar(50)")]
		public string FK_Campus_NO
		{
			get
			{
				return this._FK_Campus_NO;
			}
			set
			{
				if ((this._FK_Campus_NO != value))
				{
					if (this._Base_Campus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Campus_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Campus_NO = value;
					this.SendPropertyChanged("FK_Campus_NO");
					this.OnFK_Campus_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SPE_NO", DbType="NVarChar(50)")]
		public string FK_SPE_NO
		{
			get
			{
				return this._FK_SPE_NO;
			}
			set
			{
				if ((this._FK_SPE_NO != value))
				{
					if (this._Fresh_SPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SPE_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_SPE_NO = value;
					this.SendPropertyChanged("FK_SPE_NO");
					this.OnFK_SPE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_Class_Fresh_Counseller", Storage="_Fresh_Counsellers", ThisKey="PK_Class_NO", OtherKey="FK_Class_NO")]
		public EntitySet<Fresh_Counseller> Fresh_Counsellers
		{
			get
			{
				return this._Fresh_Counsellers;
			}
			set
			{
				this._Fresh_Counsellers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Fresh_Class", Storage="_Fresh_SPE", ThisKey="FK_SPE_NO", OtherKey="PK_SPE", IsForeignKey=true)]
		internal Fresh_SPE Fresh_SPE
		{
			get
			{
				return this._Fresh_SPE.Entity;
			}
			set
			{
				Fresh_SPE previousValue = this._Fresh_SPE.Entity;
				if (((previousValue != value) 
							|| (this._Fresh_SPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fresh_SPE.Entity = null;
						previousValue.Fresh_Classes.Remove(this);
					}
					this._Fresh_SPE.Entity = value;
					if ((value != null))
					{
						value.Fresh_Classes.Add(this);
						this._FK_SPE_NO = value.PK_SPE;
					}
					else
					{
						this._FK_SPE_NO = default(string);
					}
					this.SendPropertyChanged("Fresh_SPE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_Campus_Fresh_Class", Storage="_Base_Campus", ThisKey="FK_Campus_NO", OtherKey="PK_Campus", IsForeignKey=true)]
		internal Base_Campus Base_Campus
		{
			get
			{
				return this._Base_Campus.Entity;
			}
			set
			{
				Base_Campus previousValue = this._Base_Campus.Entity;
				if (((previousValue != value) 
							|| (this._Base_Campus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Base_Campus.Entity = null;
						previousValue.Fresh_Classes.Remove(this);
					}
					this._Base_Campus.Entity = value;
					if ((value != null))
					{
						value.Fresh_Classes.Add(this);
						this._FK_Campus_NO = value.PK_Campus;
					}
					else
					{
						this._FK_Campus_NO = default(string);
					}
					this.SendPropertyChanged("Base_Campus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fresh_Counsellers(Fresh_Counseller entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_Class = this;
		}
		
		private void detach_Fresh_Counsellers(Fresh_Counseller entity)
		{
			this.SendPropertyChanging();
			entity.Fresh_Class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_College")]
	public partial class Base_College : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_College;
		
		private string _Name;
		
		private string _Enabled;
		
		private string _College_NO;
		
		private EntitySet<Base_Staff> _Base_Staffs;
		
		private EntitySet<Fresh_SPE> _Fresh_SPEs;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CollegeChanging(string value);
    partial void OnPK_CollegeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEnabledChanging(string value);
    partial void OnEnabledChanged();
    partial void OnCollege_NOChanging(string value);
    partial void OnCollege_NOChanged();
    #endregion
		
		public Base_College()
		{
			this._Base_Staffs = new EntitySet<Base_Staff>(new Action<Base_Staff>(this.attach_Base_Staffs), new Action<Base_Staff>(this.detach_Base_Staffs));
			this._Fresh_SPEs = new EntitySet<Fresh_SPE>(new Action<Fresh_SPE>(this.attach_Fresh_SPEs), new Action<Fresh_SPE>(this.detach_Fresh_SPEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_College", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_College
		{
			get
			{
				return this._PK_College;
			}
			set
			{
				if ((this._PK_College != value))
				{
					this.OnPK_CollegeChanging(value);
					this.SendPropertyChanging();
					this._PK_College = value;
					this.SendPropertyChanged("PK_College");
					this.OnPK_CollegeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this.OnEnabledChanging(value);
					this.SendPropertyChanging();
					this._Enabled = value;
					this.SendPropertyChanged("Enabled");
					this.OnEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_College_NO", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string College_NO
		{
			get
			{
				return this._College_NO;
			}
			set
			{
				if ((this._College_NO != value))
				{
					this.OnCollege_NOChanging(value);
					this.SendPropertyChanging();
					this._College_NO = value;
					this.SendPropertyChanged("College_NO");
					this.OnCollege_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_College_Base_Staff", Storage="_Base_Staffs", ThisKey="PK_College", OtherKey="FK_College_NO")]
		public EntitySet<Base_Staff> Base_Staffs
		{
			get
			{
				return this._Base_Staffs;
			}
			set
			{
				this._Base_Staffs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_College_Fresh_SPE", Storage="_Fresh_SPEs", ThisKey="PK_College", OtherKey="FK_College_Code")]
		public EntitySet<Fresh_SPE> Fresh_SPEs
		{
			get
			{
				return this._Fresh_SPEs;
			}
			set
			{
				this._Fresh_SPEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Base_Staffs(Base_Staff entity)
		{
			this.SendPropertyChanging();
			entity.Base_College = this;
		}
		
		private void detach_Base_Staffs(Base_Staff entity)
		{
			this.SendPropertyChanging();
			entity.Base_College = null;
		}
		
		private void attach_Fresh_SPEs(Fresh_SPE entity)
		{
			this.SendPropertyChanging();
			entity.Base_College = this;
		}
		
		private void detach_Fresh_SPEs(Fresh_SPE entity)
		{
			this.SendPropertyChanging();
			entity.Base_College = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_Campus")]
	public partial class Base_Campus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Campus;
		
		private string _Campus_NO;
		
		private string _Campus_Name;
		
		private string _Enabled;
		
		private EntitySet<Fresh_Class> _Fresh_Classes;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_CampusChanging(string value);
    partial void OnPK_CampusChanged();
    partial void OnCampus_NOChanging(string value);
    partial void OnCampus_NOChanged();
    partial void OnCampus_NameChanging(string value);
    partial void OnCampus_NameChanged();
    partial void OnEnabledChanging(string value);
    partial void OnEnabledChanged();
    #endregion
		
		public Base_Campus()
		{
			this._Fresh_Classes = new EntitySet<Fresh_Class>(new Action<Fresh_Class>(this.attach_Fresh_Classes), new Action<Fresh_Class>(this.detach_Fresh_Classes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Campus", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Campus
		{
			get
			{
				return this._PK_Campus;
			}
			set
			{
				if ((this._PK_Campus != value))
				{
					this.OnPK_CampusChanging(value);
					this.SendPropertyChanging();
					this._PK_Campus = value;
					this.SendPropertyChanged("PK_Campus");
					this.OnPK_CampusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campus_NO", DbType="NVarChar(20)")]
		public string Campus_NO
		{
			get
			{
				return this._Campus_NO;
			}
			set
			{
				if ((this._Campus_NO != value))
				{
					this.OnCampus_NOChanging(value);
					this.SendPropertyChanging();
					this._Campus_NO = value;
					this.SendPropertyChanged("Campus_NO");
					this.OnCampus_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Campus_Name", DbType="NVarChar(50)")]
		public string Campus_Name
		{
			get
			{
				return this._Campus_Name;
			}
			set
			{
				if ((this._Campus_Name != value))
				{
					this.OnCampus_NameChanging(value);
					this.SendPropertyChanging();
					this._Campus_Name = value;
					this.SendPropertyChanged("Campus_Name");
					this.OnCampus_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="NVarChar(10)")]
		public string Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this.OnEnabledChanging(value);
					this.SendPropertyChanging();
					this._Enabled = value;
					this.SendPropertyChanged("Enabled");
					this.OnEnabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_Campus_Fresh_Class", Storage="_Fresh_Classes", ThisKey="PK_Campus", OtherKey="FK_Campus_NO")]
		public EntitySet<Fresh_Class> Fresh_Classes
		{
			get
			{
				return this._Fresh_Classes;
			}
			set
			{
				this._Fresh_Classes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Base_Campus = this;
		}
		
		private void detach_Fresh_Classes(Fresh_Class entity)
		{
			this.SendPropertyChanging();
			entity.Base_Campus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Fresh_Counseller")]
	public partial class Fresh_Counseller : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_Counseller_NO;
		
		private string _FK_Class_NO;
		
		private string _FK_Staff_NO;
		
		private string _Year;
		
		private string _Phone;
		
		private string _QQ;
		
		private EntityRef<Fresh_Class> _Fresh_Class;
		
		private EntityRef<Base_Staff> _Base_Staff;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_Counseller_NOChanging(string value);
    partial void OnPK_Counseller_NOChanged();
    partial void OnFK_Class_NOChanging(string value);
    partial void OnFK_Class_NOChanged();
    partial void OnFK_Staff_NOChanging(string value);
    partial void OnFK_Staff_NOChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    #endregion
		
		public Fresh_Counseller()
		{
			this._Fresh_Class = default(EntityRef<Fresh_Class>);
			this._Base_Staff = default(EntityRef<Base_Staff>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_Counseller_NO", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_Counseller_NO
		{
			get
			{
				return this._PK_Counseller_NO;
			}
			set
			{
				if ((this._PK_Counseller_NO != value))
				{
					this.OnPK_Counseller_NOChanging(value);
					this.SendPropertyChanging();
					this._PK_Counseller_NO = value;
					this.SendPropertyChanged("PK_Counseller_NO");
					this.OnPK_Counseller_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Class_NO", DbType="NVarChar(50)")]
		public string FK_Class_NO
		{
			get
			{
				return this._FK_Class_NO;
			}
			set
			{
				if ((this._FK_Class_NO != value))
				{
					if (this._Fresh_Class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Class_NO = value;
					this.SendPropertyChanged("FK_Class_NO");
					this.OnFK_Class_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Staff_NO", DbType="NVarChar(50)")]
		public string FK_Staff_NO
		{
			get
			{
				return this._FK_Staff_NO;
			}
			set
			{
				if ((this._FK_Staff_NO != value))
				{
					if (this._Base_Staff.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_Staff_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Staff_NO = value;
					this.SendPropertyChanged("FK_Staff_NO");
					this.OnFK_Staff_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(20)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="NVarChar(20)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_Class_Fresh_Counseller", Storage="_Fresh_Class", ThisKey="FK_Class_NO", OtherKey="PK_Class_NO", IsForeignKey=true)]
		internal Fresh_Class Fresh_Class
		{
			get
			{
				return this._Fresh_Class.Entity;
			}
			set
			{
				Fresh_Class previousValue = this._Fresh_Class.Entity;
				if (((previousValue != value) 
							|| (this._Fresh_Class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fresh_Class.Entity = null;
						previousValue.Fresh_Counsellers.Remove(this);
					}
					this._Fresh_Class.Entity = value;
					if ((value != null))
					{
						value.Fresh_Counsellers.Add(this);
						this._FK_Class_NO = value.PK_Class_NO;
					}
					else
					{
						this._FK_Class_NO = default(string);
					}
					this.SendPropertyChanged("Fresh_Class");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Base_Staff_Fresh_Counseller", Storage="_Base_Staff", ThisKey="FK_Staff_NO", OtherKey="PK_Staff_NO", IsForeignKey=true)]
		internal Base_Staff Base_Staff
		{
			get
			{
				return this._Base_Staff.Entity;
			}
			set
			{
				Base_Staff previousValue = this._Base_Staff.Entity;
				if (((previousValue != value) 
							|| (this._Base_Staff.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Base_Staff.Entity = null;
						previousValue.Fresh_Counsellers.Remove(this);
					}
					this._Base_Staff.Entity = value;
					if ((value != null))
					{
						value.Fresh_Counsellers.Add(this);
						this._FK_Staff_NO = value.PK_Staff_NO;
					}
					else
					{
						this._FK_Staff_NO = default(string);
					}
					this.SendPropertyChanged("Base_Staff");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Base_STU")]
	public partial class Base_STU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PK_SNO;
		
		private string _FK_SPE_Code;
		
		private string _Year;
		
		private string _Test_NO;
		
		private string _ID_NO;
		
		private string _Name;
		
		private string _Gender_Code;
		
		private string _Photo;
		
		private string _Status_Code;
		
		private System.Nullable<System.DateTime> _DT_Initial;
		
		private string _FK_Class_NO;
		
		private string _Password;
		
		private string _QQ;
		
		private string _Phone;
		
		private EntityRef<Fresh_SPE> _Fresh_SPE;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPK_SNOChanging(string value);
    partial void OnPK_SNOChanged();
    partial void OnFK_SPE_CodeChanging(string value);
    partial void OnFK_SPE_CodeChanged();
    partial void OnYearChanging(string value);
    partial void OnYearChanged();
    partial void OnTest_NOChanging(string value);
    partial void OnTest_NOChanged();
    partial void OnID_NOChanging(string value);
    partial void OnID_NOChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnGender_CodeChanging(string value);
    partial void OnGender_CodeChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnStatus_CodeChanging(string value);
    partial void OnStatus_CodeChanged();
    partial void OnDT_InitialChanging(System.Nullable<System.DateTime> value);
    partial void OnDT_InitialChanged();
    partial void OnFK_Class_NOChanging(string value);
    partial void OnFK_Class_NOChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnQQChanging(string value);
    partial void OnQQChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public Base_STU()
		{
			this._Fresh_SPE = default(EntityRef<Fresh_SPE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PK_SNO", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PK_SNO
		{
			get
			{
				return this._PK_SNO;
			}
			set
			{
				if ((this._PK_SNO != value))
				{
					this.OnPK_SNOChanging(value);
					this.SendPropertyChanging();
					this._PK_SNO = value;
					this.SendPropertyChanged("PK_SNO");
					this.OnPK_SNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SPE_Code", DbType="NVarChar(50)")]
		public string FK_SPE_Code
		{
			get
			{
				return this._FK_SPE_Code;
			}
			set
			{
				if ((this._FK_SPE_Code != value))
				{
					if (this._Fresh_SPE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SPE_CodeChanging(value);
					this.SendPropertyChanging();
					this._FK_SPE_Code = value;
					this.SendPropertyChanged("FK_SPE_Code");
					this.OnFK_SPE_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="NVarChar(10)")]
		public string Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_NO", DbType="NVarChar(20)")]
		public string Test_NO
		{
			get
			{
				return this._Test_NO;
			}
			set
			{
				if ((this._Test_NO != value))
				{
					this.OnTest_NOChanging(value);
					this.SendPropertyChanging();
					this._Test_NO = value;
					this.SendPropertyChanged("Test_NO");
					this.OnTest_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NO", DbType="NVarChar(20)")]
		public string ID_NO
		{
			get
			{
				return this._ID_NO;
			}
			set
			{
				if ((this._ID_NO != value))
				{
					this.OnID_NOChanging(value);
					this.SendPropertyChanging();
					this._ID_NO = value;
					this.SendPropertyChanged("ID_NO");
					this.OnID_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(20)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender_Code", DbType="NVarChar(10)")]
		public string Gender_Code
		{
			get
			{
				return this._Gender_Code;
			}
			set
			{
				if ((this._Gender_Code != value))
				{
					this.OnGender_CodeChanging(value);
					this.SendPropertyChanging();
					this._Gender_Code = value;
					this.SendPropertyChanged("Gender_Code");
					this.OnGender_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(255)")]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this.OnPhotoChanging(value);
					this.SendPropertyChanging();
					this._Photo = value;
					this.SendPropertyChanged("Photo");
					this.OnPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Code", DbType="NVarChar(10)")]
		public string Status_Code
		{
			get
			{
				return this._Status_Code;
			}
			set
			{
				if ((this._Status_Code != value))
				{
					this.OnStatus_CodeChanging(value);
					this.SendPropertyChanging();
					this._Status_Code = value;
					this.SendPropertyChanged("Status_Code");
					this.OnStatus_CodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Initial", DbType="DateTime")]
		public System.Nullable<System.DateTime> DT_Initial
		{
			get
			{
				return this._DT_Initial;
			}
			set
			{
				if ((this._DT_Initial != value))
				{
					this.OnDT_InitialChanging(value);
					this.SendPropertyChanging();
					this._DT_Initial = value;
					this.SendPropertyChanged("DT_Initial");
					this.OnDT_InitialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Class_NO", DbType="NVarChar(50)")]
		public string FK_Class_NO
		{
			get
			{
				return this._FK_Class_NO;
			}
			set
			{
				if ((this._FK_Class_NO != value))
				{
					this.OnFK_Class_NOChanging(value);
					this.SendPropertyChanging();
					this._FK_Class_NO = value;
					this.SendPropertyChanged("FK_Class_NO");
					this.OnFK_Class_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QQ", DbType="NVarChar(20)")]
		public string QQ
		{
			get
			{
				return this._QQ;
			}
			set
			{
				if ((this._QQ != value))
				{
					this.OnQQChanging(value);
					this.SendPropertyChanging();
					this._QQ = value;
					this.SendPropertyChanged("QQ");
					this.OnQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Fresh_SPE_Base_STU", Storage="_Fresh_SPE", ThisKey="FK_SPE_Code", OtherKey="PK_SPE", IsForeignKey=true)]
		public Fresh_SPE Fresh_SPE
		{
			get
			{
				return this._Fresh_SPE.Entity;
			}
			set
			{
				Fresh_SPE previousValue = this._Fresh_SPE.Entity;
				if (((previousValue != value) 
							|| (this._Fresh_SPE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Fresh_SPE.Entity = null;
						previousValue.Base_STUs.Remove(this);
					}
					this._Fresh_SPE.Entity = value;
					if ((value != null))
					{
						value.Base_STUs.Add(this);
						this._FK_SPE_Code = value.PK_SPE;
					}
					else
					{
						this._FK_SPE_Code = default(string);
					}
					this.SendPropertyChanged("Fresh_SPE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
