<?xml version="1.0" encoding="utf-8"?><Database Name="yxxt_data" Class="organizationModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=118.114.252.173,20933;Initial Catalog=yxxt_data;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="yxxt_dataConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Base_Staff" Member="Base_Staffs">
    <Type Name="Base_Staff">
      <Column Name="PK_Staff_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FK_College_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_Class" Member="Fresh_Classes">
    <Type Name="Fresh_Class">
      <Column Name="PK_Class_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Campus_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_SPE_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Base_College" Member="Base_Colleges">
    <Type Name="Base_College">
      <Column Name="PK_College" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Enabled" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="College_NO" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Base_Campus" Member="Base_Campus">
    <Type Name="Base_Campus">
      <Column Name="PK_Campus" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Campus_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Campus_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_Counseller" Member="Fresh_Counsellers">
    <Type Name="Fresh_Counseller">
      <Column Name="PK_Counseller_NO" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Class_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FK_Staff_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_Confirm" Member="Fresh_Confirms">
    <Type Name="Fresh_Confirm">
      <Column Name="PK_Confirm_ID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_SNO" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Confirm_state" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Confirm_Date" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Fresh_SPE" Member="Fresh_SPEs">
    <Type Name="Fresh_SPE">
      <Column Name="SPE_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SPE_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDU_Level_Code" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FK_College_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PK_SPE" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Base_STU" Member="Base_STUs">
    <Type Name="Base_STU">
      <Column Name="PK_SNO" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_SPE_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Year" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Test_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ID_NO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Gender_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DT_Initial" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_Class_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QQ" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Height" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Weight" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Nation_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Census" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Politics_Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Home_add" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Base_Code" Member="Base_Codes">
    <Type Name="Base_Code">
      <Column Name="PK_Code" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Code_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Base_Code_Item" Member="Base_Code_Items">
    <Type Name="Base_Code_Item">
      <Column Name="PK_Item" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FK_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Item_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Item_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>