<?xml version="1.0" encoding="utf-8"?><Database Name="zypt_data" Class="userDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.35.10.53;Initial Catalog=zypt_data;Persist Security Info=True;User ID=host2015" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zypt_dataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.yonghqx" Member="yonghqx">
    <Type Name="yonghqx">
      <Column Name="guid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="yhqx" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lsz" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="yhid" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="xm" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="lxdh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="yxdm" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pjjxbmdm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pjbmdm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="uumzw" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="banji" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="kecheng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="yhdh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dltime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fwcs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="yhzp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="file_json" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="privacy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qq" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="summary" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="user_status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>