<?xml version="1.0" encoding="utf-8"?><Database Name="zypt_data" Class="zy_filesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.35.10.53;Initial Catalog=zypt_data;Persist Security Info=True;User ID=host2015" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zypt_dataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ZY_FILES" Member="ZY_FILES">
    <Type Name="ZY_FILES">
      <Column Name="guid" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phy_add" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="logic_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="up_dt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cr_dt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ed_dt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="md5" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="suffix" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="up_user" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="play_add" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ZY_FILES_MAPPING" Member="ZY_FILES_MAPPING">
    <Type Name="ZY_FILES_MAPPING">
      <Column Name="mapping_id" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_guid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phy_add" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="mapping_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_type" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="file_size" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="map_dt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="first_uploader" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="map_status" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="play_add" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
</Database>